### ISSUE TITLE
Broken link to Binder

### ISSUE THREAD

**Issue by jonbrenas** [malariagen/vector-data#83]
On the Ag3.0 page (and maybe others?), there is a link to MyBinder <https://gke.mybinder.org/> which is broken (it goes to a page with only `default backend - 404`). The same is true on any page (that is a notebook) when clicking on the rocket and selecting `Binder`.

**Comment by leehart** [comment]
Hi @ahernank, @jonbrenas . Should the "Binder" link (as well as the "Colab" link, via #94) be removed?

Currently the "Binder" link (rocket ship) still appears, and leads to an error page, i.e. "500: Internal Server Error".

E.g. https://malariagen.github.io/vector-data/af1/af1.0.html
- https://mybinder.org/v2/gh/malariagen/vector-data/master?urlpath=lab/tree/docs/af1/af1.0.ipynb

I'm a bit confused because I thought that this issue (and PR #91) were meant to resolve this?

**Comment by leehart** [comment]
Looks like just removing `binderhub_url` (or `colab_url`) won't do the trick. (Nobody checked!)

This https://github.com/jupyter-book/jupyter-book/issues/1428 suggests that we need to set those options to empty strings instead.

**Comment by ahernank** [comment]
Thanks so much for picking-up @leehart! I have on my big list a to-do to open a new issue describing the button bit only -- as when we talked about this, we only mentioned the text. But yup, as it doesn't happen on the training repo, I was hoping to come around to checking the actual config on there but great to hear the empty strings might do the trick.
